export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CLUB_DATA =  'CLUB_DATA';
export const UPDATE_CLUB_DATA = 'UPDATE_CLUB_DATA';
export const FILTER_CLUB_DATA = 'FILTER_CLUB_DATA ';
export const SEARCH_CLUB_DATA = 'SEARCH_CLUB_DATA';
export const SAVE_PLAYERDETAILS = 'SAVE_PLAYERDETAILS';